on:
  create

permissions: read-all

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
    - name: post to traQ
      uses: SSlime-s/traq-webhook@v4.12
      with:
        webhook-id: ${{ secrets.WEBHOOK_ID }}
        webhook-secret: ${{ secrets.WEBHOOK_SECRET }}
